In [1]:
import numpy as np

### Creating and Saving NumPy ndarrays

In [2]:
a = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float32)

In [3]:
a

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [4]:
# rank
a.ndim

2

In [5]:
# shape
a.shape

(2, 3)

In [6]:
# dtype
a.dtype

dtype('float32')

In [7]:
# number of elements
a.size

6

In [8]:
x = np.array(['Hello', 'World!'])

print('x = ', x)
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x =  ['Hello' 'World!']
x has dimensions: (2,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: <U6


In [9]:
# save
x = np.array([1, 2, 3, 4, 5], dtype=np.float32)
# np.save('my_array', x)

In [10]:
# y = np.load('my_array.npy')

In [11]:
# y.dtype

In [12]:
# y.shape

### Using Built-in Functions to Create ndarrays

In [13]:
X = np.zeros((3, 4))
X

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
X = np.ones((3, 2), dtype=np.int64)
X

array([[1, 1],
       [1, 1],
       [1, 1]])

In [15]:
X = np.full((2, 3), 42.0, dtype=np.int32)
X

array([[42, 42, 42],
       [42, 42, 42]], dtype=int32)

In [16]:
# We create a 5 x 5 Identity matrix. 
X = np.eye(5)
X

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
X = np.diag([10, 20, 30, 50])
X

array([[10,  0,  0,  0],
       [ 0, 20,  0,  0],
       [ 0,  0, 30,  0],
       [ 0,  0,  0, 50]])

In [18]:
X = np.diag(np.full((3,), 42))
X

array([[42,  0,  0],
       [ 0, 42,  0],
       [ 0,  0, 42]])

In [19]:
# numpy.arange([start, ]stop, [step, ]dtype=None)
X = np.arange(10)
X


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
X = np.arange(4, 10)
X

array([4, 5, 6, 7, 8, 9])

In [21]:
X = np.arange(1, 14, 3)
X

array([ 1,  4,  7, 10, 13])

In [22]:
# numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
X = np.linspace(0, 25, 3)
X

array([ 0. , 12.5, 25. ])

In [23]:
X = np.linspace(0, 25, 10, endpoint=False)
X

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. , 22.5])

In [24]:
# numpy.reshape(array, newshape, order='C')[source]


In [25]:
X = np.arange(20)
X = np.reshape(X, (4, 5))
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [26]:
# ndarray.reshape(shape, order='C')
# numpy.ndarray.reshape - This one is a Method
X = np.arange(20).reshape(4, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [27]:
X = np.linspace(0, 50, 10, endpoint=False).reshape(5, 2)
X

array([[ 0.,  5.],
       [10., 15.],
       [20., 25.],
       [30., 35.],
       [40., 45.]])

### Create a Numpy array using the numpy.random.random() function

In [28]:
X = np.random.random((3, 3))
X

array([[0.41366889, 0.0591782 , 0.79961295],
       [0.22518476, 0.61016103, 0.9424096 ],
       [0.95697018, 0.82007262, 0.79881694]])

In [29]:
# numpy.random.randint(start, stop, size = shape)
X = np.random.randint(4, 15, size=(3, 2))
X

array([[13,  8],
       [10, 10],
       [14, 13]])

In [30]:
# np.random.normal(mean, standard deviation, size=shape)
X = np.random.normal(0, 0.1, size=(5, 3))
X

array([[ 0.13559833,  0.05409308, -0.05665034],
       [-0.10188091, -0.04234158,  0.03765956],
       [ 0.18120558,  0.01449803, -0.25862254],
       [-0.12651051,  0.11449053,  0.0543404 ],
       [-0.03096517, -0.02957467, -0.10853666]])

### Accessing, Deleting, and Inserting Elements Into ndarrays


In [31]:
x = np.array([1, 2, 3, 4, 5])

# Let's access some elements with positive indices
print('This is First Element in x:', x[0])
print('This is Second Element in x:', x[1])
print('This is Fifth (Last) Element in x:', x[4])
print()

# Let's access the same elements with negative indices
print('This is First Element in x:', x[-5])
print('This is Second Element in x:', x[-4])
print('This is Fifth (Last) Element in x:', x[-1])
x

This is First Element in x: 1
This is Second Element in x: 2
This is Fifth (Last) Element in x: 5

This is First Element in x: 1
This is Second Element in x: 2
This is Fifth (Last) Element in x: 5


array([1, 2, 3, 4, 5])

In [32]:
x = np.array([1, 2, 3, 4, 5])
x[3] = 20
x

array([ 1,  2,  3, 20,  5])

In [33]:
# To access elements in rank 2 ndarrays we need to provide 2 indices in the form [row, column].

X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
X

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
# Let's access some elements in X
print('This is (0,0) Element in X:', X[0, 0])
print('This is (0,1) Element in X:', X[0, 1])
print('This is (2,2) Element in X:', X[2, 2])

This is (0,0) Element in X: 1
This is (0,1) Element in X: 2
This is (2,2) Element in X: 9


In [35]:
X[0, 0] = 20
X

array([[20,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [36]:
# np.delete(ndarray, elements, axis)
# For rank 2 ndarrays, axis = 0 is used to select rows, and axis = 1 is used to select columns.

x = np.array([1, 2, 3, 4, 5])
x = np.delete(x, [0, 2, 4])
x

array([2, 4])

In [37]:
Y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
Y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
w = np.delete(Y, 0, axis=0)
w

array([[4, 5, 6],
       [7, 8, 9]])

In [39]:
v = np.delete(Y, [0, 2], axis=1)
v

array([[2],
       [5],
       [8]])

In [40]:
Y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
# numpy.append(array, values, axis=None)
x = np.array([1, 2, 3, 4, 5])
x = np.append(x, 6)
x = np.append(x, [7, 8])
x

array([1, 2, 3, 4, 5, 6, 7, 8])

In [42]:
Y = np.array([[1, 2, 3], [4, 5, 6]])
Y

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
v = np.append(Y, [[7, 8, 9]], axis=0)
v

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
q = np.append(Y, [[9], [10]], axis=1)
q

array([[ 1,  2,  3,  9],
       [ 4,  5,  6, 10]])

In [45]:
Y

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
# np.insert(ndarray, index, elements, axis)
x = np.array([1, 2, 5, 6, 7])
x = np.insert(x, 2, [3, 4])
x

array([1, 2, 3, 4, 5, 6, 7])

In [47]:
Y = np.array([[1, 2, 3], [7, 8, 9]])
Y

array([[1, 2, 3],
       [7, 8, 9]])

In [48]:
w = np.insert(Y, 1, [4, 5, 6], axis=0)
w

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
v = np.insert(Y, 1, 42, axis=1)
v

array([[ 1, 42,  2,  3],
       [ 7, 42,  8,  9]])

In [50]:
Y

array([[1, 2, 3],
       [7, 8, 9]])

In [51]:
# numpy.hstack(sequence_of_ndarray)
# numpy.vstack(sequence_of_ndarray)
x = np.array([1, 2])
x

array([1, 2])

In [52]:
Y = np.array([[3, 4], [5, 6]])
Y

array([[3, 4],
       [5, 6]])

In [53]:
z = np.vstack((x, Y))
z

array([[1, 2],
       [3, 4],
       [5, 6]])

In [54]:
w = np.hstack((Y, x.reshape(2, 1)))
w

array([[3, 4, 1],
       [5, 6, 2]])

In [55]:
Y

array([[3, 4],
       [5, 6]])

### Slicing ndarrays

In [56]:
# 1. ndarray[start:end]
# 2. ndarray[start:]
# 3. ndarray[:end]

X = np.arange(20).reshape(4, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [57]:
Z = X[1:4, 2:5]
Z

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [58]:
W = X[1:, 2:5]
W

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [59]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [60]:
Y = X[:3, 2:5]
Y

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])

In [61]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [62]:
v = X[2, :]
v

array([10, 11, 12, 13, 14])

In [63]:
q = X[:, 2]
q

array([ 2,  7, 12, 17])

In [64]:
# We select all the elements in the 3rd column but return a rank 2 ndarray
R = X[:, 2:3]
R

array([[ 2],
       [ 7],
       [12],
       [17]])

In [65]:
R.shape

(4, 1)

In the above examples, when we make assignments, such as:

Z = X[1:4,2:5]

the slice of the original array X is not copied in the variable Z. Rather, X and Z are now just two different names for the same ndarray. We say that slicing only creates a view of the original array. This means that if you make changes in Z you will be in effect changing the elements in X as well.

In [66]:
X = np.arange(20).reshape(4, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [67]:
Z = X[1:4, 2:5]
Z

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [68]:
Z[2, 2] = 555
X

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18, 555]])

In [69]:
# ndarray.copy(order='C')
X = np.arange(20).reshape(4, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [70]:
Z = np.copy(X[1:4, 2:5])
Z

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [71]:
W = X[1:4, 2:5].copy()
W

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [72]:
Z[2, 2] = 555
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [73]:
W[2, 2] = 444
Z

array([[  7,   8,   9],
       [ 12,  13,  14],
       [ 17,  18, 555]])

In [74]:
# Use an array as indices to either make slices, select, or change elements

X = np.arange(20).reshape(4, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [75]:
indices = np.array([1, 3])
Y = X[indices, :]
Y

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19]])

In [76]:
Z = X[:, indices]
Z

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18]])

In [77]:
X = np.random.randint(1, 20, size=(50, 5))
X

array([[14, 15, 11, 16,  4],
       [ 5, 11,  3,  1,  7],
       [17, 15, 19,  6, 16],
       [14,  3, 18, 14,  4],
       [ 5, 16,  5,  1, 18],
       [16,  6,  9,  1,  2],
       [ 5, 10, 19, 10,  2],
       [14, 17, 16,  3, 18],
       [12,  4, 15,  1, 18],
       [ 7, 15,  6, 16,  8],
       [18,  4,  1,  9,  5],
       [ 1,  6, 11, 17, 11],
       [ 2, 11, 19,  8, 15],
       [ 8,  3,  1,  4, 19],
       [17,  3, 17, 16, 18],
       [ 9, 18, 14,  5, 16],
       [12, 10, 18, 16,  4],
       [ 3,  9, 11,  2, 13],
       [10,  9,  3, 10,  6],
       [18,  5,  6, 14,  9],
       [18, 12, 15, 19, 15],
       [ 1,  7, 13,  1, 16],
       [10,  3, 12, 11, 16],
       [ 9, 12, 12,  2,  3],
       [ 4, 12, 19, 16,  2],
       [ 8, 17,  7,  5,  4],
       [13,  6,  8, 14, 10],
       [16,  3, 12, 16, 12],
       [19, 11, 15, 18,  3],
       [10, 18, 17,  2, 14],
       [ 4,  2,  5, 19, 17],
       [15, 17,  4,  6, 15],
       [18,  2,  9,  7, 10],
       [ 9, 16,  3,  4,  4],
       [ 9,  6

In [78]:
row_indices = np.random.randint(0, 50, size=10)
row_indices

array([ 9, 32,  7, 49,  7, 17,  5, 40,  3, 33])

In [79]:
X_subset = X[row_indices, :]
X_subset

array([[ 7, 15,  6, 16,  8],
       [18,  2,  9,  7, 10],
       [14, 17, 16,  3, 18],
       [17,  2, 16, 17, 19],
       [14, 17, 16,  3, 18],
       [ 3,  9, 11,  2, 13],
       [16,  6,  9,  1,  2],
       [10, 14, 17,  2, 19],
       [14,  3, 18, 14,  4],
       [ 9, 16,  3,  4,  4]])

In [80]:
X_subset = X[row_indices[4:8], :]
X_subset

array([[14, 17, 16,  3, 18],
       [ 3,  9, 11,  2, 13],
       [16,  6,  9,  1,  2],
       [10, 14, 17,  2, 19]])

In [81]:
# numpy.diag(ndarray, k=N)
# It extracts or constructs the diagonal elements
# As default is k=0, which refers to the main diagonal
# Values of k > 0 are used to select elements in diagonals above the main diagonal
# Values of k < 0 are used to select elements in diagonals below the main diagonal

X = np.arange(25).reshape(5, 5)
X


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [82]:
np.diag(X)

array([ 0,  6, 12, 18, 24])

In [83]:
np.diag(X, k=1)

array([ 1,  7, 13, 19])

In [84]:
np.diag(X, k=-1)

array([ 5, 11, 17, 23])

In [85]:
# numpy.unique(array, return_index=False, return_inverse=False, return_counts=False, axis=None)
X = np.array([[1, 2, 3], [5, 2, 8], [1, 2, 3]])
np.unique(X)

array([1, 2, 3, 5, 8])

### Boolean Indexing, Set Operations, and Sorting

In [86]:
X = np.arange(25).reshape(5, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [87]:
X[X > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [88]:
X[3:5, 4:5]

array([[19],
       [24]])

In [89]:
X[X <= 7]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [90]:
X[(X > 10) & (X < 17)]

array([11, 12, 13, 14, 15, 16])

In [91]:
# assign
X[(X > 10) & (X < 17)] = -1
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, -1, -1, -1, -1],
       [-1, -1, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [92]:
# set operations
x = np.array([1, 2, 3, 4, 5])
y = np.array([6, 7, 2, 8, 4])

In [93]:
np.intersect1d(x, y)

array([2, 4])

In [94]:
np.setdiff1d(x, y)

array([1, 3, 5])

In [95]:
np.union1d(x, y)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [96]:
# numpy.ndarray.sort method
# ndarray.sort(axis=-1, kind=None, order=None)

# When numpy.sort() is used as a function, it sorts the ndrrays out of place
# When you use numpy.ndarray.sort() as a method, ndarray.sort() sorts the ndarray in place

x = np.random.randint(1, 11, size=(10,))
x

array([ 4,  8,  4, 10,  4,  7, 10, 10,  1, 10])

In [97]:
y = np.sort(x)
y

array([ 1,  4,  4,  4,  7,  8, 10, 10, 10, 10])

In [98]:
x

array([ 4,  8,  4, 10,  4,  7, 10, 10,  1, 10])

In [99]:
x.sort()
x

array([ 1,  4,  4,  4,  7,  8, 10, 10, 10, 10])

In [100]:
np.unique(x)

array([ 1,  4,  7,  8, 10])

In [101]:
# numpy.sort function
# numpy.sort(array, axis=-1, kind=None, order=None)
# It can take values in the range -1 to (ndim-1)
# Default value is axis = -1, which sorts along the last axis
# If axis = None is specified, the array is flattened before sorting. It will return a 1-D array
# If axis = 0 - sort column
# If axis = 1 - sort row

In [102]:
X = np.random.randint(1, 11, size=(5, 5))
X

array([[ 2,  6,  5,  7,  4],
       [ 8,  7,  6,  8,  1],
       [10,  8,  8,  3,  7],
       [ 8,  6,  9,  7,  1],
       [10,  9,  2,  8,  3]])

In [103]:
Y = np.sort(X, axis=0)
Y

array([[ 2,  6,  2,  3,  1],
       [ 8,  6,  5,  7,  1],
       [ 8,  7,  6,  7,  3],
       [10,  8,  8,  8,  4],
       [10,  9,  9,  8,  7]])

In [104]:
Y = np.sort(X, axis=1)
Y

array([[ 2,  4,  5,  6,  7],
       [ 1,  6,  7,  8,  8],
       [ 3,  7,  8,  8, 10],
       [ 1,  6,  7,  8,  9],
       [ 2,  3,  8,  9, 10]])

### Arithmetic operations and Broadcasting

In [105]:
# element wise operations
x = np.array([1, 2, 3, 4])
y = np.array([2, 3, 4, 5])

In [106]:
x + y

array([3, 5, 7, 9])

In [107]:
z = np.add(x, y)
z

array([3, 5, 7, 9])

In [108]:
x - y

array([-1, -1, -1, -1])

In [109]:
z = np.subtract(x, y)
z

array([-1, -1, -1, -1])

In [110]:
x * y

array([ 2,  6, 12, 20])

In [111]:
z = np.multiply(x, y)
z

array([ 2,  6, 12, 20])

In [112]:
x / y

array([0.5       , 0.66666667, 0.75      , 0.8       ])

In [113]:
z = np.divide(x, y)
z

array([0.5       , 0.66666667, 0.75      , 0.8       ])

In [114]:
X = np.array([1, 2, 3, 4]).reshape(2, 2)
X

array([[1, 2],
       [3, 4]])

In [115]:
Y = np.array([5.5, 6.5, 7.5, 8.5]).reshape(2, 2)
Y

array([[5.5, 6.5],
       [7.5, 8.5]])

In [116]:
X + Y

array([[ 6.5,  8.5],
       [10.5, 12.5]])

In [117]:
z = np.add(X, Y)
z

array([[ 6.5,  8.5],
       [10.5, 12.5]])

In [118]:
X - Y

array([[-4.5, -4.5],
       [-4.5, -4.5]])

In [119]:
z = np.subtract(X, Y)
z

array([[-4.5, -4.5],
       [-4.5, -4.5]])

In [120]:
X * Y

array([[ 5.5, 13. ],
       [22.5, 34. ]])

In [121]:
z = np.multiply(X, Y)
z

array([[ 5.5, 13. ],
       [22.5, 34. ]])

In [122]:
X / Y

array([[0.18181818, 0.30769231],
       [0.4       , 0.47058824]])

In [123]:
z = np.divide(X, Y)
z

array([[0.18181818, 0.30769231],
       [0.4       , 0.47058824]])

In [124]:
# math functions
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [125]:
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [126]:
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [127]:
np.power(x, 2)

array([ 1,  4,  9, 16])

In [128]:
# statistical functions
X = np.array([[1, 2], [3, 4]])
X

array([[1, 2],
       [3, 4]])

In [129]:
X.mean()

2.5

In [130]:
X.mean(axis=0)

array([2., 3.])

In [131]:
X.mean(axis=1)

array([1.5, 3.5])

In [132]:
X.sum()

10

In [133]:
X.sum(axis=0)

array([4, 6])

In [134]:
X.sum(axis=1)

array([3, 7])

In [135]:
X.std()

1.118033988749895

In [136]:
X.std(axis=0)

array([1., 1.])

In [137]:
X.std(axis=1)

array([0.5, 0.5])

In [138]:
np.median(X)

2.5

In [139]:
np.median(X, axis=0)

array([2., 3.])

In [140]:
np.median(X, axis=1)

array([1.5, 3.5])

In [141]:
X.max()

4

In [142]:
X.max(axis=0)

array([3, 4])

In [143]:
X.max(axis=1)

array([2, 4])

In [144]:
X.max(axis=1)

array([2, 4])

In [145]:
# consts
X = np.array([[1, 2], [3, 4]])
X

array([[1, 2],
       [3, 4]])

In [146]:
3 * X

array([[ 3,  6],
       [ 9, 12]])

In [147]:
X * 3

array([[ 3,  6],
       [ 9, 12]])

In [148]:
3 + X

array([[4, 5],
       [6, 7]])

In [149]:
X - 3

array([[-2, -1],
       [ 0,  1]])

In [150]:
X / 3

array([[0.33333333, 0.66666667],
       [1.        , 1.33333333]])

In [151]:
# element wise operations
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [152]:
Y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
Y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [153]:
Z = np.array([1, 2, 3]).reshape(3, 1)
Z

array([[1],
       [2],
       [3]])

In [154]:
x + Y

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [155]:
Z + Y

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [156]:
# broadcasting
# https://numpy.org/doc/stable/user/basics.broadcasting.html

In [157]:
# https://numpy.org/doc/stable/reference/routines.math.html

In [158]:
# https://numpy.org/doc/2.0/reference/generated/numpy.matrix.html

In [161]:
# DOT PRODUCT VS MATMUL
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
dot_product_1d = np.dot(x, y)
dot_product_1d

32

In [160]:
# 2-D arrays (matrix multiplication)
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
dot_product_2d = np.dot(A, B)
# [[1*5+2*7, 1*6+2*8], [3*5+4*7, 3*6+4*8]] = [[5+14, 6+16], [15+28, 18+32]] = [[19, 22], [43, 50]]
print(f"A = \n{A}")
print(f"B = \n{B}")
print(f"Dot product of A and B (matrix multiplication):\n{dot_product_2d}")
print("Using A @ B for matrix multiplication (preferred for 2D):")
print(A @ B)
print("Using np.matmul(A, B) for matrix multiplication (preferred for 2D):")
print(np.matmul(A, B))
print("-" * 20)

A = 
[[1 2]
 [3 4]]
B = 
[[5 6]
 [7 8]]
Dot product of A and B (matrix multiplication):
[[19 22]
 [43 50]]
Using A @ B for matrix multiplication (preferred for 2D):
[[19 22]
 [43 50]]
Using np.matmul(A, B) for matrix multiplication (preferred for 2D):
[[19 22]
 [43 50]]
--------------------


In [162]:
# Scalar multiplication
scalar = 3
arr = np.array([1, 2, 3])
dot_product_scalar_arr = np.dot(scalar, arr)
print(f"scalar = {scalar}")
print(f"arr = {arr}")
print(f"Dot product of scalar and arr: {dot_product_scalar_arr}")
print(f"Using scalar * arr: {scalar * arr}") # Preferred
print("-" * 20)

scalar = 3
arr = [1 2 3]
Dot product of scalar and arr: [3 6 9]
Using scalar * arr: [3 6 9]
--------------------


In [163]:
# N-D array and 1-D array
C = np.arange(12).reshape(2, 2, 3) # Shape (2, 2, 3)
d = np.array([1, 0, 1])            # Shape (3,)
dot_product_nd_1d = np.dot(C, d)
# C[0,0,:] = [0,1,2], dot([0,1,2], [1,0,1]) = 0*1 + 1*0 + 2*1 = 2
# C[0,1,:] = [3,4,5], dot([3,4,5], [1,0,1]) = 3*1 + 4*0 + 5*1 = 8
# C[1,0,:] = [6,7,8], dot([6,7,8], [1,0,1]) = 6*1 + 7*0 + 8*1 = 14
# C[1,1,:] = [9,10,11], dot([9,10,11], [1,0,1]) = 9*1 + 10*0 + 11*1 = 20
# Result shape (2,2)
print(f"C (shape {C.shape}) = \n{C}")
print(f"d (shape {d.shape}) = {d}")
print(f"Dot product of C and d (shape {dot_product_nd_1d.shape}):\n{dot_product_nd_1d}")
print("-" * 20)

C (shape (2, 2, 3)) = 
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
d (shape (3,)) = [1 0 1]
Dot product of C and d (shape (2, 2)):
[[ 2  8]
 [14 20]]
--------------------
