In [5]:
import numpy as np

### Creating and Saving NumPy ndarrays

In [6]:
a = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float32)

In [7]:
a

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [8]:
# rank
a.ndim

2

In [9]:
# shape
a.shape

(2, 3)

In [10]:
# dtype
a.dtype

dtype('float32')

In [11]:
# number of elements
a.size

6

In [12]:
x = np.array(['Hello', 'World!'])

print('x = ', x)
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x =  ['Hello' 'World!']
x has dimensions: (2,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: <U6


In [13]:
# save
x = np.array([1, 2, 3, 4, 5], dtype=np.float32)
# np.save('my_array', x)

In [14]:
# y = np.load('my_array.npy')

In [15]:
# y.dtype

In [16]:
# y.shape

### Using Built-in Functions to Create ndarrays

In [17]:
X = np.zeros((3, 4))
X

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
X = np.ones((3, 2), dtype=np.int64)
X

array([[1, 1],
       [1, 1],
       [1, 1]])

In [19]:
X = np.full((2, 3), 42.0, dtype=np.int32)
X

array([[42, 42, 42],
       [42, 42, 42]], dtype=int32)

In [20]:
# We create a 5 x 5 Identity matrix. 
X = np.eye(5)
X

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
X = np.diag([10, 20, 30, 50])
X

array([[10,  0,  0,  0],
       [ 0, 20,  0,  0],
       [ 0,  0, 30,  0],
       [ 0,  0,  0, 50]])

In [22]:
X = np.diag(np.full((3,), 42))
X

array([[42,  0,  0],
       [ 0, 42,  0],
       [ 0,  0, 42]])

In [23]:
# numpy.arange([start, ]stop, [step, ]dtype=None)
X = np.arange(10)
X


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
X = np.arange(4, 10)
X

array([4, 5, 6, 7, 8, 9])

In [25]:
X = np.arange(1, 14, 3)
X

array([ 1,  4,  7, 10, 13])

In [26]:
# numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
X = np.linspace(0, 25, 3)
X

array([ 0. , 12.5, 25. ])

In [27]:
X = np.linspace(0, 25, 10, endpoint=False)
X

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. , 22.5])

In [28]:
# numpy.reshape(array, newshape, order='C')[source]


In [29]:
X = np.arange(20)
X = np.reshape(X, (4, 5))
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [30]:
# ndarray.reshape(shape, order='C')
# numpy.ndarray.reshape - This one is a Method
X = np.arange(20).reshape(4, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [31]:
X = np.linspace(0, 50, 10, endpoint=False).reshape(5, 2)
X

array([[ 0.,  5.],
       [10., 15.],
       [20., 25.],
       [30., 35.],
       [40., 45.]])

### Create a Numpy array using the numpy.random.random() function

In [32]:
X = np.random.random((3, 3))
X

array([[0.34193009, 0.56603947, 0.9571815 ],
       [0.3835523 , 0.32188151, 0.33789988],
       [0.20995353, 0.76976893, 0.39342547]])

In [33]:
# numpy.random.randint(start, stop, size = shape)
X = np.random.randint(4, 15, size=(3, 2))
X

array([[10,  5],
       [ 6, 10],
       [ 5, 11]])

In [34]:
# np.random.normal(mean, standard deviation, size=shape)
X = np.random.normal(0, 0.1, size=(5, 3))
X

array([[ 0.15610711,  0.06787578, -0.10918658],
       [ 0.01543785, -0.0340525 ,  0.09284656],
       [-0.09695686,  0.13153549,  0.04186234],
       [ 0.16692306, -0.11822374, -0.14131691],
       [-0.07975947, -0.08793184, -0.00899351]])

### Accessing, Deleting, and Inserting Elements Into ndarrays


In [35]:
x = np.array([1, 2, 3, 4, 5])

# Let's access some elements with positive indices
print('This is First Element in x:', x[0])
print('This is Second Element in x:', x[1])
print('This is Fifth (Last) Element in x:', x[4])
print()

# Let's access the same elements with negative indices
print('This is First Element in x:', x[-5])
print('This is Second Element in x:', x[-4])
print('This is Fifth (Last) Element in x:', x[-1])
x

This is First Element in x: 1
This is Second Element in x: 2
This is Fifth (Last) Element in x: 5

This is First Element in x: 1
This is Second Element in x: 2
This is Fifth (Last) Element in x: 5


array([1, 2, 3, 4, 5])

In [36]:
x = np.array([1, 2, 3, 4, 5])
x[3] = 20
x

array([ 1,  2,  3, 20,  5])

In [37]:
# To access elements in rank 2 ndarrays we need to provide 2 indices in the form [row, column].

X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
X

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
# Let's access some elements in X
print('This is (0,0) Element in X:', X[0, 0])
print('This is (0,1) Element in X:', X[0, 1])
print('This is (2,2) Element in X:', X[2, 2])

This is (0,0) Element in X: 1
This is (0,1) Element in X: 2
This is (2,2) Element in X: 9


In [39]:
X[0, 0] = 20
X

array([[20,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [40]:
# np.delete(ndarray, elements, axis)
# For rank 2 ndarrays, axis = 0 is used to select rows, and axis = 1 is used to select columns.

x = np.array([1, 2, 3, 4, 5])
x = np.delete(x, [0, 2, 4])
x

array([2, 4])

In [41]:
Y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
Y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
w = np.delete(Y, 0, axis=0)
w

array([[4, 5, 6],
       [7, 8, 9]])

In [43]:
v = np.delete(Y, [0, 2], axis=1)
v

array([[2],
       [5],
       [8]])

In [44]:
Y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
# numpy.append(array, values, axis=None)
x = np.array([1, 2, 3, 4, 5])
x = np.append(x, 6)
x = np.append(x, [7, 8])
x

array([1, 2, 3, 4, 5, 6, 7, 8])

In [46]:
Y = np.array([[1, 2, 3], [4, 5, 6]])
Y

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
v = np.append(Y, [[7, 8, 9]], axis=0)
v

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
q = np.append(Y, [[9], [10]], axis=1)
q

array([[ 1,  2,  3,  9],
       [ 4,  5,  6, 10]])

In [49]:
Y

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
# np.insert(ndarray, index, elements, axis)
x = np.array([1, 2, 5, 6, 7])
x = np.insert(x, 2, [3, 4])
x

array([1, 2, 3, 4, 5, 6, 7])

In [51]:
Y = np.array([[1, 2, 3], [7, 8, 9]])
Y

array([[1, 2, 3],
       [7, 8, 9]])

In [52]:
w = np.insert(Y, 1, [4, 5, 6], axis=0)
w

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
v = np.insert(Y, 1, 42, axis=1)
v

array([[ 1, 42,  2,  3],
       [ 7, 42,  8,  9]])

In [54]:
Y

array([[1, 2, 3],
       [7, 8, 9]])

In [55]:
# numpy.hstack(sequence_of_ndarray)
# numpy.vstack(sequence_of_ndarray)
x = np.array([1, 2])
x

array([1, 2])

In [56]:
Y = np.array([[3, 4], [5, 6]])
Y

array([[3, 4],
       [5, 6]])

In [57]:
z = np.vstack((x, Y))
z

array([[1, 2],
       [3, 4],
       [5, 6]])

In [58]:
w = np.hstack((Y, x.reshape(2, 1)))
w

array([[3, 4, 1],
       [5, 6, 2]])

In [59]:
Y

array([[3, 4],
       [5, 6]])

### Slicing ndarrays

In [60]:
# 1. ndarray[start:end]
# 2. ndarray[start:]
# 3. ndarray[:end]

X = np.arange(20).reshape(4, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [61]:
Z = X[1:4, 2:5]
Z

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [62]:
W = X[1:, 2:5]
W

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [63]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [64]:
Y = X[:3, 2:5]
Y

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])

In [65]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [66]:
v = X[2, :]
v

array([10, 11, 12, 13, 14])

In [67]:
q = X[:, 2]
q

array([ 2,  7, 12, 17])

In [68]:
# We select all the elements in the 3rd column but return a rank 2 ndarray
R = X[:, 2:3]
R

array([[ 2],
       [ 7],
       [12],
       [17]])

In [69]:
R.shape

(4, 1)

In the above examples, when we make assignments, such as:

Z = X[1:4,2:5]

the slice of the original array X is not copied in the variable Z. Rather, X and Z are now just two different names for the same ndarray. We say that slicing only creates a view of the original array. This means that if you make changes in Z you will be in effect changing the elements in X as well.

In [70]:
X = np.arange(20).reshape(4, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [71]:
Z = X[1:4, 2:5]
Z

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [72]:
Z[2, 2] = 555
X

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18, 555]])

In [73]:
# ndarray.copy(order='C')
X = np.arange(20).reshape(4, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [74]:
Z = np.copy(X[1:4, 2:5])
Z

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [75]:
W = X[1:4, 2:5].copy()
W

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [76]:
Z[2, 2] = 555
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [77]:
W[2, 2] = 444
Z

array([[  7,   8,   9],
       [ 12,  13,  14],
       [ 17,  18, 555]])

In [78]:
# Use an array as indices to either make slices, select, or change elements

X = np.arange(20).reshape(4, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [79]:
indices = np.array([1, 3])
Y = X[indices, :]
Y

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19]])

In [80]:
Z = X[:, indices]
Z

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18]])

In [81]:
X = np.random.randint(1, 20, size=(50, 5))
X

array([[18, 15,  6,  8,  9],
       [17, 18, 12,  4, 17],
       [ 3,  6,  4, 13, 19],
       [10, 16, 16,  2, 13],
       [ 9, 16, 15, 17,  8],
       [ 6,  5,  9,  3,  3],
       [11,  7, 15, 15, 19],
       [ 7,  3, 12,  4, 19],
       [12,  3,  6, 14,  8],
       [15, 16,  5, 16,  8],
       [ 1,  5, 17, 13,  5],
       [ 1,  4,  6, 17,  8],
       [ 7,  9,  6, 11,  1],
       [14,  4, 12,  5, 13],
       [14,  4, 11,  9,  8],
       [ 3, 13, 12, 19, 13],
       [ 3, 15, 16, 18, 10],
       [18, 11,  8,  7,  8],
       [ 6,  8, 18,  8, 12],
       [15,  9,  7, 19, 14],
       [ 4, 16,  6, 17, 17],
       [10,  7, 18, 17,  8],
       [ 9, 14, 17, 16, 14],
       [ 7, 11, 15,  4,  6],
       [11,  1,  6,  3,  8],
       [ 7, 15,  6, 10,  3],
       [16,  2, 11,  6, 13],
       [ 9,  4, 18,  3, 13],
       [ 9,  5,  8,  3, 12],
       [ 7,  6,  9,  8,  7],
       [10, 17,  4,  3, 14],
       [16, 11,  3,  9,  2],
       [19, 12,  1,  1,  5],
       [ 6, 16,  6,  9,  1],
       [ 6,  2

In [82]:
row_indices = np.random.randint(0, 50, size=10)
row_indices

array([45, 22,  8, 44, 44, 43, 37, 35, 13, 36])

In [83]:
X_subset = X[row_indices, :]
X_subset

array([[ 8,  4, 18, 14,  4],
       [ 9, 14, 17, 16, 14],
       [12,  3,  6, 14,  8],
       [10, 18,  4, 17, 13],
       [10, 18,  4, 17, 13],
       [14, 12,  1,  6, 19],
       [11,  3, 11, 11, 16],
       [ 8, 17, 12, 13,  7],
       [14,  4, 12,  5, 13],
       [ 7, 15, 17, 13, 10]])

In [84]:
X_subset = X[row_indices[4:8], :]
X_subset

array([[10, 18,  4, 17, 13],
       [14, 12,  1,  6, 19],
       [11,  3, 11, 11, 16],
       [ 8, 17, 12, 13,  7]])

In [85]:
# numpy.diag(ndarray, k=N)
# It extracts or constructs the diagonal elements
# As default is k=0, which refers to the main diagonal
# Values of k > 0 are used to select elements in diagonals above the main diagonal
# Values of k < 0 are used to select elements in diagonals below the main diagonal

X = np.arange(25).reshape(5, 5)
X


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [86]:
np.diag(X)

array([ 0,  6, 12, 18, 24])

In [87]:
np.diag(X, k=1)

array([ 1,  7, 13, 19])

In [88]:
np.diag(X, k=-1)

array([ 5, 11, 17, 23])

In [89]:
# numpy.unique(array, return_index=False, return_inverse=False, return_counts=False, axis=None)
X = np.array([[1, 2, 3], [5, 2, 8], [1, 2, 3]])
np.unique(X)

array([1, 2, 3, 5, 8])

### Boolean Indexing, Set Operations, and Sorting

In [90]:
X = np.arange(25).reshape(5, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [91]:
X[X > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [92]:
X[3:5, 4:5]

array([[19],
       [24]])

In [93]:
X[X <= 7]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [94]:
X[(X > 10) & (X < 17)]

array([11, 12, 13, 14, 15, 16])

In [95]:
# assign
X[(X > 10) & (X < 17)] = -1
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, -1, -1, -1, -1],
       [-1, -1, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [96]:
# set operations
x = np.array([1, 2, 3, 4, 5])
y = np.array([6, 7, 2, 8, 4])

In [97]:
np.intersect1d(x, y)

array([2, 4])

In [98]:
np.setdiff1d(x, y)

array([1, 3, 5])

In [99]:
np.union1d(x, y)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [100]:
# numpy.ndarray.sort method
# ndarray.sort(axis=-1, kind=None, order=None)

# When numpy.sort() is used as a function, it sorts the ndrrays out of place
# When you use numpy.ndarray.sort() as a method, ndarray.sort() sorts the ndarray in place

x = np.random.randint(1, 11, size=(10,))
x

array([ 3,  6,  5,  7,  3, 10,  6,  1,  5, 10])

In [101]:
y = np.sort(x)
y

array([ 1,  3,  3,  5,  5,  6,  6,  7, 10, 10])

In [102]:
x

array([ 3,  6,  5,  7,  3, 10,  6,  1,  5, 10])

In [103]:
x.sort()
x

array([ 1,  3,  3,  5,  5,  6,  6,  7, 10, 10])

In [104]:
np.unique(x)

array([ 1,  3,  5,  6,  7, 10])

In [105]:
# numpy.sort function
# numpy.sort(array, axis=-1, kind=None, order=None)
# It can take values in the range -1 to (ndim-1)
# Default value is axis = -1, which sorts along the last axis
# If axis = None is specified, the array is flattened before sorting. It will return a 1-D array
# If axis = 0 - sort column
# If axis = 1 - sort row

In [106]:
X = np.random.randint(1, 11, size=(5, 5))
X

array([[10,  2,  1,  5,  5],
       [ 4,  8,  8,  6, 10],
       [ 3,  1,  1,  3,  8],
       [ 8, 10,  5,  2,  6],
       [ 7,  7,  9,  3, 10]])

In [107]:
Y = np.sort(X, axis=0)
Y

array([[ 3,  1,  1,  2,  5],
       [ 4,  2,  1,  3,  6],
       [ 7,  7,  5,  3,  8],
       [ 8,  8,  8,  5, 10],
       [10, 10,  9,  6, 10]])

In [108]:
Y = np.sort(X, axis=1)
Y

array([[ 1,  2,  5,  5, 10],
       [ 4,  6,  8,  8, 10],
       [ 1,  1,  3,  3,  8],
       [ 2,  5,  6,  8, 10],
       [ 3,  7,  7,  9, 10]])

### Arithmetic operations and Broadcasting

In [109]:
# element wise operations
x = np.array([1, 2, 3, 4])
y = np.array([2, 3, 4, 5])

In [110]:
x + y

array([3, 5, 7, 9])

In [111]:
z = np.add(x, y)
z

array([3, 5, 7, 9])

In [112]:
x - y

array([-1, -1, -1, -1])

In [113]:
z = np.subtract(x, y)
z

array([-1, -1, -1, -1])

In [114]:
x * y

array([ 2,  6, 12, 20])

In [115]:
z = np.multiply(x, y)
z

array([ 2,  6, 12, 20])

In [116]:
x / y

array([0.5       , 0.66666667, 0.75      , 0.8       ])

In [117]:
z = np.divide(x, y)
z

array([0.5       , 0.66666667, 0.75      , 0.8       ])

In [118]:
X = np.array([1, 2, 3, 4]).reshape(2, 2)
X

array([[1, 2],
       [3, 4]])

In [119]:
Y = np.array([5.5, 6.5, 7.5, 8.5]).reshape(2, 2)
Y

array([[5.5, 6.5],
       [7.5, 8.5]])

In [120]:
X + Y

array([[ 6.5,  8.5],
       [10.5, 12.5]])

In [121]:
z = np.add(X, Y)
z

array([[ 6.5,  8.5],
       [10.5, 12.5]])

In [122]:
X - Y

array([[-4.5, -4.5],
       [-4.5, -4.5]])

In [123]:
z = np.subtract(X, Y)
z

array([[-4.5, -4.5],
       [-4.5, -4.5]])

In [124]:
X * Y

array([[ 5.5, 13. ],
       [22.5, 34. ]])

In [125]:
z = np.multiply(X, Y)
z

array([[ 5.5, 13. ],
       [22.5, 34. ]])

In [126]:
X / Y

array([[0.18181818, 0.30769231],
       [0.4       , 0.47058824]])

In [127]:
z = np.divide(X, Y)
z

array([[0.18181818, 0.30769231],
       [0.4       , 0.47058824]])

In [128]:
# math functions
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [129]:
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [130]:
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [131]:
np.power(x, 2)

array([ 1,  4,  9, 16])

In [132]:
# statistical functions
X = np.array([[1, 2], [3, 4]])
X

array([[1, 2],
       [3, 4]])

In [133]:
X.mean()

2.5

In [134]:
X.mean(axis=0)

array([2., 3.])

In [135]:
X.mean(axis=1)

array([1.5, 3.5])

In [136]:
X.sum()

10

In [137]:
X.sum(axis=0)

array([4, 6])

In [138]:
X.sum(axis=1)

array([3, 7])

In [139]:
X.std()

1.118033988749895

In [140]:
X.std(axis=0)

array([1., 1.])

In [141]:
X.std(axis=1)

array([0.5, 0.5])

In [142]:
np.median(X)

2.5

In [143]:
np.median(X, axis=0)

array([2., 3.])

In [144]:
np.median(X, axis=1)

array([1.5, 3.5])

In [145]:
X.max()

4

In [146]:
X.max(axis=0)

array([3, 4])

In [147]:
X.max(axis=1)

array([2, 4])

In [148]:
X.max(axis=1)

array([2, 4])

In [149]:
# consts
X = np.array([[1, 2], [3, 4]])
X

array([[1, 2],
       [3, 4]])

In [150]:
3 * X

array([[ 3,  6],
       [ 9, 12]])

In [151]:
X * 3

array([[ 3,  6],
       [ 9, 12]])

In [152]:
3 + X

array([[4, 5],
       [6, 7]])

In [153]:
X - 3

array([[-2, -1],
       [ 0,  1]])

In [154]:
X / 3

array([[0.33333333, 0.66666667],
       [1.        , 1.33333333]])

In [155]:
# element wise operations
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [156]:
Y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
Y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [157]:
Z = np.array([1, 2, 3]).reshape(3, 1)
Z

array([[1],
       [2],
       [3]])

In [158]:
x + Y

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [159]:
Z + Y

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [160]:
# broadcasting
# https://numpy.org/doc/stable/user/basics.broadcasting.html

In [161]:
# https://numpy.org/doc/stable/reference/routines.math.html

In [162]:
# https://numpy.org/doc/2.0/reference/generated/numpy.matrix.html

In [163]:
# DOT PRODUCT VS MATMUL
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
dot_product_1d = np.dot(x, y)
dot_product_1d

32

In [164]:
# 2-D arrays (matrix multiplication)
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
dot_product_2d = np.dot(A, B)
# [[1*5+2*7, 1*6+2*8], [3*5+4*7, 3*6+4*8]] = [[5+14, 6+16], [15+28, 18+32]] = [[19, 22], [43, 50]]
print(f"A = \n{A}")
print(f"B = \n{B}")
print(f"Dot product of A and B (matrix multiplication):\n{dot_product_2d}")
print("Using A @ B for matrix multiplication (preferred for 2D):")
print(A @ B)
print("Using np.matmul(A, B) for matrix multiplication (preferred for 2D):")
print(np.matmul(A, B))
print("-" * 20)

A = 
[[1 2]
 [3 4]]
B = 
[[5 6]
 [7 8]]
Dot product of A and B (matrix multiplication):
[[19 22]
 [43 50]]
Using A @ B for matrix multiplication (preferred for 2D):
[[19 22]
 [43 50]]
Using np.matmul(A, B) for matrix multiplication (preferred for 2D):
[[19 22]
 [43 50]]
--------------------


In [165]:
# Scalar multiplication
scalar = 3
arr = np.array([1, 2, 3])
dot_product_scalar_arr = np.dot(scalar, arr)
print(f"scalar = {scalar}")
print(f"arr = {arr}")
print(f"Dot product of scalar and arr: {dot_product_scalar_arr}")
print(f"Using scalar * arr: {scalar * arr}") # Preferred
print("-" * 20)

scalar = 3
arr = [1 2 3]
Dot product of scalar and arr: [3 6 9]
Using scalar * arr: [3 6 9]
--------------------


In [166]:
# N-D array and 1-D array
C = np.arange(12).reshape(2, 2, 3) # Shape (2, 2, 3)
d = np.array([1, 0, 1])            # Shape (3,)
dot_product_nd_1d = np.dot(C, d)
# C[0,0,:] = [0,1,2], dot([0,1,2], [1,0,1]) = 0*1 + 1*0 + 2*1 = 2
# C[0,1,:] = [3,4,5], dot([3,4,5], [1,0,1]) = 3*1 + 4*0 + 5*1 = 8
# C[1,0,:] = [6,7,8], dot([6,7,8], [1,0,1]) = 6*1 + 7*0 + 8*1 = 14
# C[1,1,:] = [9,10,11], dot([9,10,11], [1,0,1]) = 9*1 + 10*0 + 11*1 = 20
# Result shape (2,2)
print(f"C (shape {C.shape}) = \n{C}")
print(f"d (shape {d.shape}) = {d}")
print(f"Dot product of C and d (shape {dot_product_nd_1d.shape}):\n{dot_product_nd_1d}")
print("-" * 20)

C (shape (2, 2, 3)) = 
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
d (shape (3,)) = [1 0 1]
Dot product of C and d (shape (2, 2)):
[[ 2  8]
 [14 20]]
--------------------


In [167]:
st = np.random.rand(20)
st

array([0.8602618 , 0.54493385, 0.98347794, 0.78120315, 0.1863919 ,
       0.64989411, 0.42637125, 0.15099578, 0.54580657, 0.99344307,
       0.0796557 , 0.5680848 , 0.76009479, 0.34869397, 0.21623682,
       0.43480192, 0.39726198, 0.89296615, 0.9769253 , 0.46935899])

In [168]:
print("Mean:", st.mean())
print("Standard Deviation:", st.std())
print("Min:", st.min())
print("Max:", st.max())
print("Median:", np.median(st))



Mean: 0.5633429916015515
Standard Deviation: 0.2835514851102068
Min: 0.07965570263885802
Max: 0.9934430737713498
Median: 0.5453702123458962


In [169]:
from scipy import stats

mode_result = stats.mode(st, keepdims=True)
print("Mode:", mode_result.mode[0])

Mode: 0.07965570263885802
