In [2]:
import numpy as np

### Creating and Saving NumPy ndarrays

In [3]:
a = np.array([[1,2,3],[4,5,6]], dtype=np.float32)

In [4]:
a

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [5]:
# rank
a.ndim

2

In [6]:
# shape
a.shape

(2, 3)

In [7]:
# dtype
a.dtype

dtype('float32')

In [8]:
# number of elements
a.size

6

In [9]:
x = np.array(['Hello', 'World!'])

print('x = ', x)
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x =  ['Hello' 'World!']
x has dimensions: (2,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: <U6


In [10]:
# save
x = np.array([1, 2, 3, 4, 5], dtype=np.float32)
# np.save('my_array', x)

In [11]:
# y = np.load('my_array.npy')

In [12]:
# y.dtype

In [13]:
# y.shape

### Using Built-in Functions to Create ndarrays

In [14]:
X = np.zeros((3,4))
X

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
X = np.ones((3,2), dtype=np.int64)
X

array([[1, 1],
       [1, 1],
       [1, 1]])

In [16]:
X = np.full((2,3), 42.0, dtype=np.int32) 
X

array([[42, 42, 42],
       [42, 42, 42]], dtype=int32)

In [17]:
# We create a 5 x 5 Identity matrix. 
X = np.eye(5)
X

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
X = np.diag([10,20,30,50])
X

array([[10,  0,  0,  0],
       [ 0, 20,  0,  0],
       [ 0,  0, 30,  0],
       [ 0,  0,  0, 50]])

In [19]:
X = np.diag(np.full((3,), 42))
X

array([[42,  0,  0],
       [ 0, 42,  0],
       [ 0,  0, 42]])

In [20]:
# numpy.arange([start, ]stop, [step, ]dtype=None)
X = np.arange(10)
X


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
X = np.arange(4,10)
X

array([4, 5, 6, 7, 8, 9])

In [22]:
X = np.arange(1,14,3)
X

array([ 1,  4,  7, 10, 13])

In [23]:
# numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
X = np.linspace(0,25,3)
X

array([ 0. , 12.5, 25. ])

In [24]:
X = np.linspace(0,25,10, endpoint = False)
X

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. , 22.5])

In [25]:
# numpy.reshape(array, newshape, order='C')[source]


In [26]:
X = np.arange(20)
X = np.reshape(X, (4,5))
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [27]:
# ndarray.reshape(shape, order='C')
# numpy.ndarray.reshape - This one is a Method
X = np.arange(20).reshape(4, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [28]:
X = np.linspace(0,50,10, endpoint=False).reshape(5,2)
X

array([[ 0.,  5.],
       [10., 15.],
       [20., 25.],
       [30., 35.],
       [40., 45.]])

### Create a Numpy array using the numpy.random.random() function

In [29]:
X = np.random.random((3,3))
X

array([[0.88741206, 0.36695828, 0.10991754],
       [0.08917223, 0.81478448, 0.70545375],
       [0.61102161, 0.31651158, 0.72778884]])

In [30]:
# numpy.random.randint(start, stop, size = shape)
X = np.random.randint(4,15,size=(3,2))
X

array([[ 6, 12],
       [ 8,  6],
       [11,  6]])

In [31]:
# np.random.normal(mean, standard deviation, size=shape)
X = np.random.normal(0, 0.1, size=(5,3))
X

array([[-0.10250971,  0.00905118, -0.05101697],
       [-0.01707676,  0.11324572, -0.02538475],
       [ 0.07713291, -0.12088383, -0.18307488],
       [-0.04350902,  0.05192645, -0.0254399 ],
       [-0.07813943, -0.1868326 , -0.14320397]])

### Accessing, Deleting, and Inserting Elements Into ndarrays


In [32]:
x = np.array([1, 2, 3, 4, 5])

# Let's access some elements with positive indices
print('This is First Element in x:', x[0])
print('This is Second Element in x:', x[1])
print('This is Fifth (Last) Element in x:', x[4])
print()

# Let's access the same elements with negative indices
print('This is First Element in x:', x[-5])
print('This is Second Element in x:', x[-4])
print('This is Fifth (Last) Element in x:', x[-1])
x

This is First Element in x: 1
This is Second Element in x: 2
This is Fifth (Last) Element in x: 5

This is First Element in x: 1
This is Second Element in x: 2
This is Fifth (Last) Element in x: 5


array([1, 2, 3, 4, 5])

In [33]:
x = np.array([1, 2, 3, 4, 5])
x[3] = 20
x

array([ 1,  2,  3, 20,  5])

In [34]:
# To access elements in rank 2 ndarrays we need to provide 2 indices in the form [row, column].

X = np.array([[1,2,3],[4,5,6],[7,8,9]])
X

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
# Let's access some elements in X
print('This is (0,0) Element in X:', X[0,0])
print('This is (0,1) Element in X:', X[0,1])
print('This is (2,2) Element in X:', X[2,2])

This is (0,0) Element in X: 1
This is (0,1) Element in X: 2
This is (2,2) Element in X: 9


In [36]:
X[0,0] = 20
X

array([[20,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [37]:
# np.delete(ndarray, elements, axis)
# For rank 2 ndarrays, axis = 0 is used to select rows, and axis = 1 is used to select columns.

x = np.array([1, 2, 3, 4, 5])
x = np.delete(x, [0,2,4])
x

array([2, 4])

In [38]:
Y = np.array([[1,2,3],[4,5,6],[7,8,9]])
Y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
w = np.delete(Y, 0, axis=0)
w

array([[4, 5, 6],
       [7, 8, 9]])

In [40]:
v = np.delete(Y, [0,2], axis=1)
v

array([[2],
       [5],
       [8]])

In [41]:
Y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
# numpy.append(array, values, axis=None)
x = np.array([1, 2, 3, 4, 5])
x = np.append(x, 6)
x = np.append(x, [7,8])
x

array([1, 2, 3, 4, 5, 6, 7, 8])

In [43]:
Y = np.array([[1,2,3],[4,5,6]])
Y

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
v = np.append(Y, [[7,8,9]], axis=0)
v

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
q = np.append(Y,[[9],[10]], axis=1)
q

array([[ 1,  2,  3,  9],
       [ 4,  5,  6, 10]])

In [46]:
Y

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
# np.insert(ndarray, index, elements, axis)
x = np.array([1, 2, 5, 6, 7])
x = np.insert(x,2,[3,4])
x

array([1, 2, 3, 4, 5, 6, 7])

In [48]:
Y = np.array([[1,2,3],[7,8,9]])
Y

array([[1, 2, 3],
       [7, 8, 9]])

In [49]:
w = np.insert(Y,1,[4,5,6],axis=0)
w

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
v = np.insert(Y,1,42, axis=1)
v

array([[ 1, 42,  2,  3],
       [ 7, 42,  8,  9]])

In [51]:
Y

array([[1, 2, 3],
       [7, 8, 9]])

In [52]:
# numpy.hstack(sequence_of_ndarray)
# numpy.vstack(sequence_of_ndarray)
x = np.array([1,2])
x

array([1, 2])

In [53]:
Y = np.array([[3,4],[5,6]])
Y

array([[3, 4],
       [5, 6]])

In [54]:
z = np.vstack((x,Y))
z

array([[1, 2],
       [3, 4],
       [5, 6]])

In [55]:
w = np.hstack((Y,x.reshape(2,1)))
w

array([[3, 4, 1],
       [5, 6, 2]])

In [56]:
Y

array([[3, 4],
       [5, 6]])

### Slicing ndarrays

In [57]:
# 1. ndarray[start:end]
# 2. ndarray[start:]
# 3. ndarray[:end]

X = np.arange(20).reshape(4, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [58]:
Z = X[1:4,2:5]
Z

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [59]:
W = X[1:,2:5]
W

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [60]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [61]:
Y = X[:3,2:5]
Y

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])

In [62]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [63]:
v = X[2,:]
v

array([10, 11, 12, 13, 14])

In [64]:
q = X[:,2]
q

array([ 2,  7, 12, 17])

In [65]:
# We select all the elements in the 3rd column but return a rank 2 ndarray
R = X[:,2:3]
R

array([[ 2],
       [ 7],
       [12],
       [17]])

In [66]:
R.shape

(4, 1)

In the above examples, when we make assignments, such as:

Z = X[1:4,2:5]

the slice of the original array X is not copied in the variable Z. Rather, X and Z are now just two different names for the same ndarray. We say that slicing only creates a view of the original array. This means that if you make changes in Z you will be in effect changing the elements in X as well.

In [67]:
X = np.arange(20).reshape(4, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [68]:
Z = X[1:4,2:5]
Z

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [69]:
Z[2,2] = 555
X

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18, 555]])

In [70]:
# ndarray.copy(order='C')
X = np.arange(20).reshape(4, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [71]:
Z = np.copy(X[1:4,2:5])
Z

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [72]:
W = X[1:4,2:5].copy()
W

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [73]:
Z[2,2] = 555
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [74]:
W[2,2] = 444
Z

array([[  7,   8,   9],
       [ 12,  13,  14],
       [ 17,  18, 555]])

In [75]:
# Use an array as indices to either make slices, select, or change elements

X = np.arange(20).reshape(4, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [76]:
indices = np.array([1,3])
Y = X[indices,:]
Y

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19]])

In [77]:
Z = X[:, indices]
Z

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18]])

In [78]:
X = np.random.randint(1,20, size=(50,5))
X

array([[18, 16, 11,  6, 18],
       [ 3,  3,  2,  6,  8],
       [15, 10,  1, 15, 11],
       [19, 19, 15, 13, 14],
       [ 5, 13, 17, 17,  5],
       [11, 19, 15,  3, 19],
       [13,  5,  2, 15,  2],
       [16, 14,  7, 12,  3],
       [ 9, 10,  2, 13,  8],
       [18,  7, 15,  8, 10],
       [16, 19,  2,  3,  1],
       [18, 16,  2,  5, 10],
       [ 3, 19, 18, 11, 11],
       [ 7, 15,  8,  3,  2],
       [ 5, 19, 14,  4, 10],
       [ 5, 16, 12,  7,  2],
       [ 9, 17,  3, 12, 14],
       [ 5,  2,  2,  9, 12],
       [18,  3, 12,  6,  6],
       [ 4, 13,  8,  3, 19],
       [12, 18,  1, 14, 10],
       [ 4, 16, 17,  1, 18],
       [18, 18,  2,  6, 12],
       [16, 16, 14, 16, 12],
       [ 6, 18,  8, 11, 11],
       [ 5,  2,  9,  6,  5],
       [19, 13,  9, 16, 16],
       [ 6, 10, 10, 15,  3],
       [ 2, 13,  8,  5,  2],
       [ 1,  3, 18,  1, 16],
       [ 5, 12, 11,  8,  1],
       [ 3, 10,  8,  5, 17],
       [16,  4, 16,  4, 16],
       [12, 10,  4, 14, 15],
       [ 4,  9

In [79]:
row_indices = np.random.randint(0,50, size=10)
row_indices

array([32, 33,  7,  4, 24, 30, 38,  4,  4, 26])

In [80]:
X_subset = X[row_indices, :]
X_subset

array([[16,  4, 16,  4, 16],
       [12, 10,  4, 14, 15],
       [16, 14,  7, 12,  3],
       [ 5, 13, 17, 17,  5],
       [ 6, 18,  8, 11, 11],
       [ 5, 12, 11,  8,  1],
       [18, 12,  2,  8, 16],
       [ 5, 13, 17, 17,  5],
       [ 5, 13, 17, 17,  5],
       [19, 13,  9, 16, 16]])

In [81]:
X_subset = X[row_indices[4:8], :]
X_subset

array([[ 6, 18,  8, 11, 11],
       [ 5, 12, 11,  8,  1],
       [18, 12,  2,  8, 16],
       [ 5, 13, 17, 17,  5]])

In [82]:
# numpy.diag(ndarray, k=N)
# It extracts or constructs the diagonal elements
# As default is k=0, which refers to the main diagonal
# Values of k > 0 are used to select elements in diagonals above the main diagonal
# Values of k < 0 are used to select elements in diagonals below the main diagonal

X = np.arange(25).reshape(5, 5)
X


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [83]:
np.diag(X)

array([ 0,  6, 12, 18, 24])

In [84]:
np.diag(X, k=1)

array([ 1,  7, 13, 19])

In [85]:
np.diag(X, k=-1)

array([ 5, 11, 17, 23])

In [86]:
# numpy.unique(array, return_index=False, return_inverse=False, return_counts=False, axis=None)
X = np.array([[1,2,3],[5,2,8],[1,2,3]])
np.unique(X)

array([1, 2, 3, 5, 8])

### Boolean Indexing, Set Operations, and Sorting

In [87]:
X = np.arange(25).reshape(5, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [88]:
X[X > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [89]:
X[3:5, 4:5]

array([[19],
       [24]])

In [90]:
X[X <= 7]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [91]:
X[(X > 10) & (X < 17)]

array([11, 12, 13, 14, 15, 16])

In [92]:
# assign
X[(X > 10) & (X < 17)] =-1
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, -1, -1, -1, -1],
       [-1, -1, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [93]:
# set operations
x = np.array([1,2,3,4,5])
y = np.array([6,7,2,8,4])

In [94]:
np.intersect1d(x,y)

array([2, 4])

In [95]:
np.setdiff1d(x,y)

array([1, 3, 5])

In [96]:
np.union1d(x,y)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [97]:
# numpy.ndarray.sort method
# ndarray.sort(axis=-1, kind=None, order=None)

# When numpy.sort() is used as a function, it sorts the ndrrays out of place
# When you use numpy.ndarray.sort() as a method, ndarray.sort() sorts the ndarray in place

x = np.random.randint(1,11,size=(10,))
x

array([ 8,  6,  5,  6,  7,  6,  8, 10,  9,  1])

In [98]:
y = np.sort(x)
y

array([ 1,  5,  6,  6,  6,  7,  8,  8,  9, 10])

In [99]:
x

array([ 8,  6,  5,  6,  7,  6,  8, 10,  9,  1])

In [100]:
x.sort()
x

array([ 1,  5,  6,  6,  6,  7,  8,  8,  9, 10])

In [101]:
np.unique(x)

array([ 1,  5,  6,  7,  8,  9, 10])

In [102]:
# numpy.sort function
# numpy.sort(array, axis=-1, kind=None, order=None)
# It can take values in the range -1 to (ndim-1)
# Default value is axis = -1, which sorts along the last axis
# If axis = None is specified, the array is flattened before sorting. It will return a 1-D array
# If axis = 0 - sort column
# If axis = 1 - sort row

In [103]:
X = np.random.randint(1,11,size=(5,5))
X

array([[ 9, 10, 10,  7,  9],
       [ 5,  2, 10,  4,  6],
       [ 6,  3,  4,  6,  8],
       [ 9,  6,  8,  7,  2],
       [ 3, 10,  2,  6,  6]])

In [104]:
Y = np.sort(X, axis = 0)
Y

array([[ 3,  2,  2,  4,  2],
       [ 5,  3,  4,  6,  6],
       [ 6,  6,  8,  6,  6],
       [ 9, 10, 10,  7,  8],
       [ 9, 10, 10,  7,  9]])

In [105]:
Y = np.sort(X, axis = 1)
Y

array([[ 7,  9,  9, 10, 10],
       [ 2,  4,  5,  6, 10],
       [ 3,  4,  6,  6,  8],
       [ 2,  6,  7,  8,  9],
       [ 2,  3,  6,  6, 10]])

### Arithmetic operations and Broadcasting

In [106]:
# element wise operations
x = np.array([1,2,3,4])
y = np.array([2,3,4,5])

In [107]:
x + y

array([3, 5, 7, 9])

In [108]:
z=np.add(x,y)
z

array([3, 5, 7, 9])

In [109]:
x - y

array([-1, -1, -1, -1])

In [110]:
z=np.subtract(x,y)
z

array([-1, -1, -1, -1])

In [111]:
x * y

array([ 2,  6, 12, 20])

In [112]:
z=np.multiply(x,y)
z

array([ 2,  6, 12, 20])

In [113]:
x / y

array([0.5       , 0.66666667, 0.75      , 0.8       ])

In [114]:
z=np.divide(x,y)
z

array([0.5       , 0.66666667, 0.75      , 0.8       ])

In [115]:
X = np.array([1,2,3,4]).reshape(2,2)
X

array([[1, 2],
       [3, 4]])

In [116]:
Y = np.array([5.5,6.5,7.5,8.5]).reshape(2,2)
Y

array([[5.5, 6.5],
       [7.5, 8.5]])

In [117]:
X+Y

array([[ 6.5,  8.5],
       [10.5, 12.5]])

In [118]:
z=np.add(X,Y)
z

array([[ 6.5,  8.5],
       [10.5, 12.5]])

In [119]:
X - Y

array([[-4.5, -4.5],
       [-4.5, -4.5]])

In [120]:
z=np.subtract(X,Y)
z

array([[-4.5, -4.5],
       [-4.5, -4.5]])

In [121]:
X * Y

array([[ 5.5, 13. ],
       [22.5, 34. ]])

In [122]:
z=np.multiply(X,Y)
z

array([[ 5.5, 13. ],
       [22.5, 34. ]])

In [123]:
X / Y

array([[0.18181818, 0.30769231],
       [0.4       , 0.47058824]])

In [124]:
z=np.divide(X,Y)
z

array([[0.18181818, 0.30769231],
       [0.4       , 0.47058824]])

In [125]:
# math functions
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [126]:
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [127]:
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [128]:
np.power(x,2)

array([ 1,  4,  9, 16])

In [129]:
# statistical functions
X = np.array([[1,2], [3,4]])
X

array([[1, 2],
       [3, 4]])

In [130]:
X.mean()

2.5

In [131]:
X.mean(axis=0)

array([2., 3.])

In [132]:
X.mean(axis=1)

array([1.5, 3.5])

In [133]:
X.sum()

10

In [134]:
X.sum(axis=0)

array([4, 6])

In [135]:
X.sum(axis=1)

array([3, 7])

In [136]:
X.std()

1.118033988749895

In [137]:
X.std(axis=0)

array([1., 1.])

In [138]:
X.std(axis=1)

array([0.5, 0.5])

In [139]:
np.median(X)

2.5

In [140]:
np.median(X,axis=0)

array([2., 3.])

In [141]:
np.median(X,axis=1)

array([1.5, 3.5])

In [142]:
X.max()

4

In [143]:
X.max(axis=0)

array([3, 4])

In [144]:
X.max(axis=1)

array([2, 4])

In [145]:
X.max(axis=1)

array([2, 4])

In [146]:
# consts
X = np.array([[1,2], [3,4]])
X

array([[1, 2],
       [3, 4]])

In [147]:
3*X

array([[ 3,  6],
       [ 9, 12]])

In [148]:
X*3

array([[ 3,  6],
       [ 9, 12]])

In [149]:
3+X

array([[4, 5],
       [6, 7]])

In [150]:
X-3

array([[-2, -1],
       [ 0,  1]])

In [151]:
X/3

array([[0.33333333, 0.66666667],
       [1.        , 1.33333333]])

In [152]:
# element wise operations
x = np.array([1,2,3])
x

array([1, 2, 3])

In [153]:
Y = np.array([[1,2,3],[4,5,6],[7,8,9]])
Y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [154]:
Z = np.array([1,2,3]).reshape(3,1)
Z

array([[1],
       [2],
       [3]])

In [155]:
x + Y

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [156]:
Z + Y

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [157]:
# broadcasting
# https://numpy.org/doc/stable/user/basics.broadcasting.html

In [158]:
# https://numpy.org/doc/stable/reference/routines.math.html

In [159]:
# https://numpy.org/doc/2.0/reference/generated/numpy.matrix.html