In [1]:
import numpy as np

In [2]:
# https://youtu.be/4c_mwnYdbhQ?si=_cqmqq_7A4ZPTvn8

In [3]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.nan

nan

In [5]:
np.inf

inf

In [12]:
a = np.array([[1,2,3], [4,5,6]])

a.ravel() # view
#a.flatten() #copy

array([1, 2, 3, 4, 5, 6])

In [13]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [14]:
a.swapaxes(0,1) # multidimentional transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [15]:
# np.concatenate()

In [17]:
# np.split()

In [ ]:
# np.random.choice()

In [ ]:
# np.random.shuffle()

In [ ]:
# np.random.permutation()

In [ ]:
# np.random.seed()

In [ ]:
# np.random.randint()

In [18]:
# copy()

In [19]:
# selection a[a<10]
# a[a%2==0]

In [ ]:
# unique()

In [ ]:
# np.sort()

In [ ]:
# np.argsort()

In [ ]:
# np.searchsorted()

In [ ]:
# np.bincount()